### ISSUE TITLE
Event: Preview za front ugraditi

### ISSUE THREAD

**Issue by Tohezonja** [byte-ink-digital/web-page#22]
Ugraditi **Preview** za front na način da se event koji i nije published i nije vidljiv javnosti vidi u Front Web, a da ga samo vidi Organizator i mi kao Tracey administratori!
Na taj način organizator može provjeriti i event card na Event calendar i ući u event i vidjeti što je pod kojim tab-om na event-u i što je na svakoj utrci te na kraju može ići na register pa vidjeti kako će izgledati obrazac prijave.
Dodati samo za preview za organizatora/Tracey admin na front-u filter za događaje koji nisu objavljeni za javnost.

**Comment by kduvnjak** [comment]
@jtomic00 ovdje složiti da te ta akcija baci na kalendar evenata i tamo možeš kao organizator ili admin Traceya vidjeti i evente koji su u statusu koji nije published na taj način imamo preview kao da je taj event već publishiran
