### ISSUE TITLE
Race/Registration form settings: Custom field ne funkcionira

### ISSUE THREAD

**Issue by Tohezonja** [byte-ink-digital/web-page#34]
Custom field-a trenutno ne funkcioniraju.

Dodati i vrste polja "Date" i "Time", jer netko može tražiti unos npr. kad je netko zadnji put trčao maraton ili koje je najbolje odtrčano vrijeme pa su i te varijante potrebne.

**Comment by kduvnjak** [comment]
Dodati ove ekstra tipove za datum i vrijeme
