### ISSUE TITLE
Složiti da se na temelju IBAN-a ili SWIFT-a dohvate podatci o banci

### ISSUE THREAD

**Issue by kduvnjak** [byte-ink-digital/web-page#36]
![Image](https://github.com/user-attachments/assets/d89ce851-7fee-4027-b47e-c8652a1f0485)

Složiti servis koji na temelju IBAN-a ili SWIFT-a dohvati podatke o banci, naziv, adresu ....

**Comment by jtomic00** [comment]
Na fronti sam vec dodala poziv servisima
<img width="1071" alt="Screenshot 2024-10-03 at 11 06 34" src="https://github.com/user-attachments/assets/ff634a90-129e-44e9-831a-aac7106376e6">

<img width="514" alt="Screenshot 2024-10-03 at 11 07 12" src="https://github.com/user-attachments/assets/4ee5eaa9-773c-44a4-a0c4-33144f069ad6">

<img width="556" alt="Screenshot 2024-10-03 at 11 07 26" src="https://github.com/user-attachments/assets/b6aeeae8-6ba3-4609-ab72-7d3a2953baf4">
