### ISSUE TITLE
Greška prilikom pokušaja logiranja

### ISSUE THREAD

**Issue by ZoranB-hub** [byte-ink-digital/web-page#40]
U slučaju pokušaja prijave s pogrešnom lozinkom, sustav upadne u petlju i ne obavijesti da je lozinka pogrešna, već se stalno pokušava ulogirati

**Comment by kduvnjak** [comment]
@jtomic00 molim te provjeri ovaj login na UAT okolini username: [murix80@gmail.com](mailto:murix80@gmail.com)  lozinka: Murix80!123 kada je neispravan password ona se beskonačno vrti petlja

**Comment by jtomic00** [comment]
Ne mogu ovo reproducirati, radi ispravno i za ispravnu i pogresnu lozinku
