### ISSUE TITLE
Event/Glavni pregled: Search ne funkcionira

### ISSUE THREAD

**Issue by Tohezonja** [byte-ink-digital/web-page#7]
Na mojoj verziji Search ne funkcionira.

Kada smo gledali na sastanku na Kristijanovoj verziji app-a onda je funkcioniralo.

**Comment by kduvnjak** [comment]
![Image](https://github.com/byte-ink-digital/web-page/assets/5759516/22b01680-89ae-4e9b-9ad6-1f5991cd4c46)

**Comment by kduvnjak** [comment]
![Image](https://github.com/byte-ink-digital/web-page/assets/5759516/192cfdce-f03b-4e73-ae49-826d7c85a914)
